export ZSH_CUSTOM=~/.local/zsh/

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd notify
unsetopt appendhistory beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

autoload -U select-word-style
select-word-style bash

eval $(dircolors $ZSH_CUSTOM/dircolors/dircolors)

plugins=(git zsh-autosuggestions zsh-completions zsh-syntax-highlighting)

for plugin in $plugins;
do
  if [ -e $ZSH_CUSTOM/plugins/ ] && [ -e $ZSH_CUSTOM/plugins/$plugin ];
  then
     source $ZSH_CUSTOM/plugins/$plugin/$plugin.zsh
  fi
done

autoload -Uz promptinit
promptinit

autoload bashcompinit
bashcompinit

# autoload -U colors
# colors

#source $ZSH_CUSTOM/themes/smt.zsh-theme

export PATH=$PATH:~/.opam/default/bin:~/.local/bin

if [ ! -S ~/.ssh/ssh_auth_sock ]; then
  eval `ssh-agent`
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l > /dev/null || ssh-add

export LESS='-R'
